name: Benchmark (Manual)

on:
  workflow_dispatch:
    inputs:
      managers:
        description: 'Space separated list of package managers to benchmark'
        required: true
        default: 'all'
      benchmarks:
        description: 'Space separated list of benchmarks to be executed'
        required: true
        default: 'all'
      fixtures:
        description: 'Space separated list of fixtures to benchmark against'
        required: true
        default: 'all'

jobs:
  benchmark:
    {{> job jobName="Benchmark" }}
      - name: install hyperfine
        run: |
          wget https://github.com/sharkdp/hyperfine/releases/download/v1.13.0/hyperfine_1.13.0_amd64.deb
          sudo dpkg -i hyperfine_1.13.0_amd64.deb
      - name: Run Benchmarks
        run: ./bin/benchmark.js -m $\{{ github.event.inputs.managers }} -b $\{{ github.event.inputs.benchmarks }} -f $\{{ github.event.inputs.fixtures }} -g
      - name: Upload Results
        uses: actions/upload-artifact@v3
        with:
          name: results
          path: results/temp/
