name: Benchmark (Manual)

on:
  workflow_dispatch:
    inputs:
      managers:
        description: 'Space separated list of package managers to benchmark'
        required: true
        default: 'all'
      benchmarks:
        description: 'Space separated list of benchmarks to be executed'
        required: true
        default: 'all'
      fixtures:
        description: 'Space separated list of fixtures to benchmark against'
        required: true
        default: 'all'

jobs:
  benchmark:
    {{> job jobName="Benchmark" }}
      {{> stepHyperfine }}
      - name: Run Benchmarks
        run: |
          ./bin/benchmark.js -m $\{{ github.event.inputs.managers }} \
            -b $\{{ github.event.inputs.benchmarks }} \
            -f $\{{ github.event.inputs.fixtures }} \
            -g --loglevel=silly
      {{> stepUpload }}
